#
# boxes - Command line filter to draw/remove ASCII boxes around text
# Copyright (c) 1999-2024 Thomas Jensen and the boxes contributors
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
# License, version 3, as published by the Free Software Foundation.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#
# Jekyll Configuration

# General metadata
name: boxes
title: boxes
description: 'Command line ASCII boxes unlimited!'
tagline: 'Command line ASCII boxes unlimited!'

# Deployment
baseurl: ''
url: 'https://boxes.thomasjensen.com'

# Social Media
github: 'ascii-boxes/boxes'
twitter_username: tj_impl
twitter:
    username: tj_impl
    card: summary
logo: images/boxes-sq-256.png
author:
    twitter: tj_impl

# Plugins from the whitelist at https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Which paths are processed by Jekyll to appear under _site/
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - build/
  - cmake-build-debug/
  - coverage/
  - datagen/
  - doc/
  - js.bat
  - node_modules/
  - out/
  - src/
  - vendor/
  - vs
  - venv/

include:
  - pages/

# Permalinks / blog post URLs
permalink: /:year/:month/:title:output_ext
future: true

# Split the what's new page into multiple pages
paginate: 10
paginate_path: /blog/page:num/

# Analytics
plausible:
    data_domain: 'boxes.thomasjensen.com'

# Minify CSS
sass:
    style: compressed

# Do not create redirects.json file
redirect_from:
    json: false

# boxes custom variables
currentVersion: '2.3.0'
link_license: 'https://raw.githubusercontent.com/ascii-boxes/boxes/v2.3.0/LICENSE'

# Page frontmatter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
